# Generated by Django 5.1.3 on 2025-03-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("BookID", models.AutoField(primary_key=True, serialize=False)),
                ("BookName", models.CharField(max_length=255)),
                ("Publisher", models.CharField(max_length=255)),
                ("ReleaseDate", models.DateField()),
                ("Amount", models.IntegerField(default=1)),
                ("InStock", models.IntegerField(default=1)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Borrowed", "Borrowed"),
                            ("Reserved", "Reserved"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Literature & Fiction", "Literature & Fiction"),
                            ("Business & Finance", "Business & Finance"),
                            ("Science & Technology", "Science & Technology"),
                            ("Children & Teenage", "Children & Teenage"),
                            ("Computing & Internet", "Computing & Internet"),
                        ],
                        default="Literature & Fiction",
                        max_length=50,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
            ],
        ),
    ]
