# Generated by Django 5.1.3 on 2025-03-08 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_borrowinfo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowinfo",
            name="ActualReturnTime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="ActualReturnTime"
            ),
        ),
        migrations.AlterField(
            model_name="borrowinfo",
            name="BookID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="books.book",
                verbose_name="BookID",
            ),
        ),
        migrations.AlterField(
            model_name="borrowinfo",
            name="BorrowTime",
            field=models.DateTimeField(auto_now_add=True, verbose_name="BorrowTime"),
        ),
        migrations.AlterField(
            model_name="borrowinfo",
            name="BorrowUserID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="BorrowUserID",
            ),
        ),
        migrations.AlterField(
            model_name="borrowinfo",
            name="ReturnTime",
            field=models.DateTimeField(verbose_name="ReturnTime"),
        ),
        migrations.AlterField(
            model_name="borrowinfo",
            name="Status",
            field=models.CharField(
                choices=[
                    ("Borrowed", "Borrowed"),
                    ("Returned", "Returned"),
                    ("Overdue", "Overdue"),
                ],
                default="Borrowed",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comment", models.TextField(verbose_name="Comment")),
                (
                    "CommentTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="CommentTime"),
                ),
                (
                    "BookID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="BookID",
                    ),
                ),
                (
                    "BorrowUserID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="BorrowUserID",
                    ),
                ),
            ],
        ),
    ]
