# Generated by Django 5.1.7 on 2025-03-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_borrowinfo_actualreturntime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Literature & Fiction', 'Literature & Fiction'), ('Business & Finance', 'Business & Finance'), ('Science & Technology', 'Science & Technology'), ('Children & Teenage', 'Children & Teenage'), ('Computing & Internet', 'Computing & Internet'), ('History', 'History')], default='Literature & Fiction', max_length=50),
        ),
    ]
